<?php
/**
 * @file
 * Code for the Photo Gallery feature.
 */

include_once 'photo_gallery.features.inc';

/**
 * Implements hook_menu_alter().
 */
function photo_gallery_menu_alter(&$items) {
  $items['node/add/photo']['access callback'] = 'photo_gallery_add_access';
}

/**
 * Access callback for node/add/photo
 */
function photo_gallery_add_access($op = 'add', $type = 'photo') {
  // allow access for anonymous user "logged in" via invite
  if (isset($_SESSION['invite_id']) && node_load($_SESSION['invite_id'])) {
    return TRUE;
  }
  
  return node_access($op, $type);
}

/**
 * Implements hook_form_alter().
 */
function photo_gallery_form_photo_node_form_alter(&$form, &$form_state, $form_id) {
  // for new photo node, set default values according to the active invite if there is one
  if (empty($form['#node']->nid)) {
    drupal_set_title(t('Upload Photo to Gallery'));
    $invite = context_get('context', 'invite_invite');
    if ($invite) {
      $name = $invite->field_invite_name_first[$invite->language][0]['value'] . ' '
        . $invite->field_invite_name_last[$invite->language][0]['value']
      ;
      $event_nid = $invite->field_invite_event[$invite->language][0]['target_id'];
      $form['field_photo_photographer'][$form['field_photo_photographer']['#language']][0]['value']['#default_value'] = $name;
      $form['field_photo_parent_node'][$form['field_photo_parent_node']['#language']]['#default_value'] = array($event_nid);
    }
  }
}

/**
 * Tell whether the currently-viewed page has photos.
 */
function photo_gallery_page_has_photos() {
  static $has_photos;
  
  if (!isset($has_photos)) {
    $has_photos = FALSE;
    if (arg(0) == 'node' && arg(1) && arg(2) != 'edit') {
      // do photos exist for this node (i.e., does this node have a gallery)?
      $photo_count = db_query(
        "SELECT COUNT(*) 
          FROM {field_data_field_photo_parent_node} pnp
          INNER JOIN {node} n ON n.vid=pnp.revision_id
          WHERE field_photo_parent_node_target_id=:viewed_nid
        ;",
        array(':viewed_nid' => arg(1))
      )->fetchField();
      if ($photo_count > 0) {
        $has_photos = TRUE;
      }
    }
  }

  return $has_photos;
}

/**
 * Implements hook_node_view().
 */
function photo_gallery_node_view($node, $view_mode, $langcode) {
  if ($view_mode === 'full') {
    $object = menu_get_object();
    if (isset($object->nid) && $object->nid === $node->nid && $node->type == 'photo') {
      // redirect photo page view to the photo's gallery
      if (isset($node->field_photo_parent_node) && !empty($node->field_photo_parent_node)) {
        $gallery_nid = $node->field_photo_parent_node[$node->language][0]['target_id'];
        if ($gallery_nid) {
          drupal_goto("node/$gallery_nid/gallery");
        }
      }
    }
  }
}